build:
  nodes:
    analysis:
      tests:
        override:
          - php-scrutinizer-run

checks:
    php:
        excluded_dependencies:
            - hiqdev/composer-config-plugin
            - phpunit/phpunit
            - fzaninotto/faker
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600
filter:
    excluded_paths:
        - config/*
        - docs/*
        - tests/*
        - vendor/*
